"""Prompt templates for correlation and textual analysis via Claude."""

CORRELATION_ANALYSIS_PROMPT = """\
You are a senior marketing analyst specializing in influencer marketing for EdTech.

You are given:
1. A cleaned JSON dataset of TripleTen advertising integrations.
2. Pre-computed aggregation tables generated by code.

Important analytical guardrails:
- Treat `Traffic Fact`, `Contacts Fact`, `has_contacts`, `cost_per_contact`, and `traffic_to_contact_rate` as the PRIMARY response outcomes for content analysis.
- Treat `Deals Fact`, `Purchase F - TOTAL`, and `cost_per_purchase` as DOWNSTREAM outcomes only.
- Never claim that content directly caused purchases. Use language such as "associated with", "linked to", or "appears alongside".
- Use the table `Scope`, `N`, `Method`, `Evidence`, and `Caveat` fields when interpreting each table.
- If a table is marked exploratory or descriptive-only, say so plainly.
- Do not recompute the table numbers yourself. Use the pre-computed values exactly as provided.

## WHAT TO DELIVER
Write a business-friendly report in English with clear sections and short explanations.

### 1. Executive Summary
Provide 5 concise bullets.
Each bullet must mention:
- the finding,
- the relevant scope,
- the confidence badge (`Reliable signal`, `Probable signal`, or `Hypothesis`),
- and whether it applies to response outcomes or downstream outcomes.

### 2. Content Influence on Response
Focus on the tables tied to response outcomes such as contacts, traffic, and cost per contact.
For each important pattern:
- explain the pattern in plain language,
- cite the relevant table id(s),
- mention the scope and sample size,
- mention the confidence badge,
- explain why the pattern matters operationally.

### 3. Downstream Sales Outcomes
Discuss purchases, deals, and cost per purchase cautiously.
Frame all purchase-related observations as downstream associations, not direct causal proof.
If the data is thin, say that these are hypotheses for further validation.

### 4. Platform and Format Readout
Compare YouTube long-form, short-form, and cross-platform-comparable views only when the table scope allows it.
Do not compare YouTube-only variables such as integration position to Reels/TikTok.
Explicitly note when TikTok is descriptive-only.

### 5. Funnel and Operational Implications
Explain where the biggest downstream drop-offs happen in the funnel.
Separate content-response issues from sales-operations issues whenever possible.

### 6. Recommendations
Provide:
- creative recommendations for improving response outcomes,
- operational recommendations for lower-funnel issues,
- platform-specific next steps,
- and 3 testable hypotheses.

## STYLE RULES
- Be specific and numeric.
- Use short paragraphs and compact bullets.
- Prefer plain language over statistical jargon.
- If mentioning statistics, translate them into simple language.
- Do not invent missing values.
- If evidence is weak, say so.

## PRE-COMPUTED TABLES
The following tables were computed by code from the merged dataset.
Use these exact numbers and metadata.

{precomputed_tables}

## RAW DATA
Use the raw JSON only for qualitative examples and individual case references.
Do not recompute core tables from scratch.

{data_json}
"""


TEXTUAL_REPORT_PROMPT = """\
You are a senior marketing analyst specializing in influencer marketing for EdTech.

You are given:
1. An existing quantitative analysis report.
2. A textual comparison between integrations with and without purchases.
3. Integration context for each textual sample.

Important guardrails:
- Treat textual findings as evidence of messaging patterns, not proof of causality.
- When referencing purchases, use language like "associated with winners" or "appears more often in winner texts".
- When the sample is small, say that the pattern is exploratory.
- Use the pre-computed textual tables exactly as given.

## TASK
Write a standalone textual analysis report in English that:
- explains what linguistic patterns appear in stronger integrations,
- connects those patterns to business actions,
- and stays cautious about overclaiming.

## REQUIRED SECTIONS
- Executive Summary
- Opening Patterns
- Transition Styles
- Persuasion Architecture
- Benefit Framings
- Pain Points
- CTA Formulations
- Text Statistics
- Specificity and Evidence
- Cross-Reference with Existing Analysis
- Winning Script Template
- Anti-Patterns
- Brief Recommendations

## STYLE RULES
- Be specific, concrete, and practical.
- Quote real phrases when available.
- Prefer "associated with" over causal wording.
- Mention sample-size limits when relevant.
- Avoid claiming phrase-level purchase lift unless the tables directly support it.

## PRE-COMPUTED TEXTUAL TABLES
{precomputed_textual_tables}

## EXISTING ANALYSIS REPORT
{existing_report}

## TEXTUAL COMPARISON DATA
{textual_comparison_json}

## INTEGRATION CONTEXT
{integration_context_json}
"""


CORRELATION_ANALYSIS_V2_PROMPT = """\
You are a senior marketing analyst specializing in influencer marketing for EdTech.
You have deep expertise in statistical interpretation and causal reasoning.

You are given:
1. A cleaned JSON dataset of TripleTen advertising integrations.
2. Pre-computed aggregation tables generated by code, organized into two layers.

## CRITICAL ANALYTICAL GUARDRAILS
- NEVER use has_contacts as an outcome variable. Use cost_per_contact and \
traffic_to_contact_rate as the continuous response outcomes.
- NEVER combine YouTube and short-form enrichment features in one comparison. \
YouTube-only features (integration position, duration bins) are scoped to \
youtube_only. Short-form features (hook type, pacing) are scoped to \
short_form_only.
- ALWAYS include effect size, confidence interval, and power statement for \
each finding.
- ALWAYS state sample size and evidence level badge for each claim.
- In Layer 2, use ONLY "associated with", "linked to", or "appears alongside" \
— never causal language such as "caused", "drove", "resulted in", or "led to".
- If a finding's power is below 50%, explicitly state this is underpowered \
and treat it as a hypothesis only.
- Do not recompute the table numbers yourself. Use the pre-computed values \
exactly as provided.

## TWO-LAYER FRAMEWORK
- **Layer 1 — Content Impact Zone**: Reach → Traffic → Contacts. These are \
response metrics that content choices can plausibly influence. Tables: C1v2, \
C2v2, Q1v2, Q2v2, C5v2, C6v2, C7v2, R1v2.
- **Layer 2 — Sales Operations Context**: Deals → Calls → Purchases. These \
are downstream outcomes influenced by sales team execution, market conditions, \
and many factors beyond content. Tables: R2v2, D1v2, D2v2, D3v2, D4v2.

## WHAT TO DELIVER
Write a business-friendly report in English with clear sections and short \
explanations.

### Section 1: Executive Summary
Provide exactly 5 concise bullets.
Each bullet must mention:
- the finding in plain language,
- the relevant scope (youtube_only, short_form_only, or all_platforms),
- the confidence badge (Reliable signal, Probable signal, or Hypothesis),
- which layer it belongs to (Layer 1 or Layer 2),
- the effect size (rho or Cliff's delta with magnitude label).

### Section 2: Layer 1 — Content Impact Zone
Focus on the causal chain: Reach → Traffic → Contacts.
Use tables C1v2, C2v2, Q1v2, Q2v2, C5v2, C6v2, C7v2.
For each important pattern:
- cite the table ID, scope, and sample size N,
- report the statistic (Spearman rho or Cliff's delta) with its 95% CI,
- report the achieved power and evidence level badge,
- explain in plain language what this means operationally \
(e.g., "Integrations placed mid-roll had 23% lower cost per contact \
than pre-roll, with a medium effect size"),
- if power < 50%, flag the finding as underpowered and treat as hypothesis.

Group findings by the metric chain:
1. What drives traffic (reach → traffic)?
2. What converts traffic to contacts (traffic → contacts)?
3. What determines cost efficiency (cost_per_contact)?

### Section 3: Layer 2 — Sales Operations Context
Focus on tables R2v2, D1v2, D2v2, D3v2, D4v2.

Begin this section with a prominent disclaimer:
> **Important**: These are downstream associations. Content choices cannot \
be credited or blamed for purchase outcomes. The gap between contacts and \
purchases is mediated by sales team performance, lead quality, market timing, \
and many other factors outside the content creator's control.

For each pattern:
- cite the table ID, scope, and sample size N,
- report the statistic with its 95% CI and power,
- use ONLY descriptive language: "associated with", "linked to", \
"appears alongside",
- explain what this means for sales operations (not content strategy).

### Section 4: Platform Comparison
Use R1v2 for cross-platform response comparison (contact rates, costs).
Use D1v2 for purchase associations — clearly labeled as Layer 2.
Rules:
- YouTube-only features (integration position, duration bins) must NEVER \
be compared with short-form features (hook type, pacing),
- cross-platform comparison is limited to metrics available on all platforms \
(contact rates, cost metrics, traffic),
- note platform sample size differences and their impact on statistical power.

### Section 5: Statistical Limitations
Provide:
- a power analysis summary table: for each key finding, show N, power, \
and whether it meets the 80% threshold,
- sample size constraints and which comparisons are most affected,
- what we CANNOT claim from this data (explicit list of 3-5 non-claims),
- ICC stability summary from the enrichment audit if available \
(which enrichment features had acceptable inter-rater reliability),
- multiple comparisons consideration: how many tests were run and \
the risk of false positives.

### Section 6: Recommendations
Separate recommendations by layer:

**Layer 1 Recommendations (Content & Creative)**:
- Based ONLY on response metrics (cost_per_contact, traffic_to_contact_rate),
- actionable by content creators and marketing team,
- tied to specific findings with evidence level badges.

**Layer 2 Recommendations (Sales Operations)**:
- Based ONLY on funnel analysis (deals, calls, purchases),
- actionable by sales team and operations,
- framed as areas to investigate, not proven optimizations.

**Testable Hypotheses**:
Provide exactly 3 testable hypotheses, each with:
- a clear null and alternative hypothesis,
- the required sample size for 80% power (based on observed effect sizes),
- the recommended study design (A/B test, observational with controls, etc.),
- the primary outcome metric.

## STYLE RULES
- Be specific and numeric.
- Use short paragraphs and compact bullets.
- Prefer plain language over statistical jargon.
- If mentioning statistics, translate them into simple language immediately.
- Do not invent missing values.
- If evidence is weak, say so plainly.
- Use tables or structured lists for comparisons.

## PRE-COMPUTED TABLES
The following tables were computed by code from the merged dataset.
Use these exact numbers and metadata.

{precomputed_tables}

## RAW DATA
Use the raw JSON only for qualitative examples and individual case references.
Do not recompute core tables from scratch.

{data_json}
"""


TEXTUAL_REPORT_V2_PROMPT = """\
You are a senior marketing analyst specializing in influencer marketing for EdTech.
You have deep expertise in linguistic analysis and messaging strategy.

You are given:
1. An existing quantitative analysis report (v2, two-layer framework).
2. A textual comparison between high-performing and low-performing integrations.
3. Integration context for each textual sample.
4. Pre-computed textual analysis tables.

## CRITICAL GUARDRAILS
- High performers = top 25% by cost efficiency (lowest cost_per_contact). \
Low performers = bottom 25% by cost efficiency (highest cost_per_contact).
- Do NOT reference purchases when describing textual patterns. The textual \
classification is based on response metrics (cost_per_contact), not sales \
outcomes.
- Use "high performers" and "low performers" — never "winners" or "losers".
- When the sample is small, say that the pattern is exploratory.
- Maintain per-platform analysis: do not mix YouTube scripts with short-form \
scripts in the same comparison.
- Use the pre-computed textual tables exactly as given.

## TASK
Write a standalone textual analysis report in English that:
- explains what linguistic patterns appear in cost-efficient integrations \
(high performers),
- contrasts them with patterns in cost-inefficient integrations \
(low performers),
- connects those patterns to actionable content improvements,
- stays cautious about overclaiming and acknowledges sample-size limits.

## REQUIRED SECTIONS

### Executive Summary
3-5 bullets summarizing the most important textual differences between \
high performers and low performers. Each bullet must mention the platform \
scope and sample size.

### Opening Patterns
How do high performers open their integrations versus low performers? \
Quote real phrases when available. Analyze per platform.

### Transition Styles
How do high performers transition from organic content to the sponsored \
segment? Compare with low performer transitions. Note platform differences.

### Persuasion Architecture
What persuasion structures (problem-solution, social proof, authority, \
scarcity, etc.) appear more in high performers? Quantify when tables allow.

### Benefit Framings
What benefits are emphasized by high performers versus low performers? \
Categorize by type (career, financial, lifestyle, skill-based).

### Pain Points
What pain points are addressed? How do high and low performers differ \
in pain point specificity and emotional resonance?

### CTA Formulations
Compare call-to-action patterns. What makes high performer CTAs more \
effective at driving traffic and contacts?

### Text Statistics
Word count, sentence length, readability differences between high and \
low performers. Use pre-computed tables.

### Specificity and Evidence
Do high performers use more specific claims, data points, testimonials, \
or concrete examples? Quantify the difference.

### Cross-Reference with Quantitative Analysis
Connect textual findings to the Layer 1 quantitative findings from the \
existing report. Which textual patterns align with the strongest \
statistical signals? Do NOT cross-reference with Layer 2 (purchases).

### High-Performer Script Template
Based on observed patterns, provide a structural template for a \
high-performing integration script. Include section-by-section guidance \
with example phrases drawn from actual high performers.

### Anti-Patterns
List 3-5 specific textual patterns that appear predominantly in \
low performers and should be avoided. Quote real examples when possible.

### Brief Recommendations
- 3 content recommendations tied to specific textual findings,
- per-platform guidance where patterns differ,
- what additional data would strengthen these conclusions.

## STYLE RULES
- Be specific, concrete, and practical.
- Quote real phrases from the data when available.
- Use "associated with high performers" rather than causal wording.
- Mention sample-size limits when relevant.
- Avoid claiming phrase-level impact unless the tables directly support it.
- Use structured lists and tables for comparisons.

## PRE-COMPUTED TEXTUAL TABLES
{precomputed_textual_tables}

## EXISTING ANALYSIS REPORT
{existing_report}

## TEXTUAL COMPARISON DATA
{textual_comparison_json}

## INTEGRATION CONTEXT
{integration_context_json}
"""


REVIEWER_RESPONSES_PROMPT = """\
You are a senior marketing data analyst preparing responses for a TripleTen \
portfolio review. You must answer three specific questions from the reviewer \
with precision, data backing, and practical recommendations.

You are given:
1. The three reviewer questions.
2. The full v2 analysis report data (two-layer framework).
3. Funnel data with stage-by-stage metrics.

## CRITICAL RULES
- Be direct and specific. No marketing fluff or vague generalities.
- Every claim must reference specific data from the report.
- Use exact numbers, percentages, and sample sizes.
- Clearly separate what the data shows from what you recommend.
- Acknowledge statistical limitations honestly.
- Structure each answer as: Problem → Analysis (with data) → \
Actionable Steps → Limitations.

## REVIEWER QUESTIONS
{questions}

## REQUIRED ANSWER STRUCTURE

For each of the three questions, provide a structured response:

### Question 1: Actionable Steps to Bridge the Calls→Purchase Gap
**Problem Statement**: Define the gap quantitatively using funnel data. \
What is the current calls-to-purchase conversion rate? How does it compare \
across platforms and segments?

**Analysis**: Use Layer 2 data (D1v2-D4v2, R2v2) to identify:
- which segments have the widest gap,
- what factors are associated with better conversion,
- where the biggest volume of lost potential sits.

Reference specific table IDs, sample sizes, and effect sizes.

**Actionable Steps**: Provide 5-7 concrete, prioritized steps. Each step must:
- describe exactly what to do,
- explain why (citing data),
- estimate the expected impact range,
- note any dependencies or prerequisites.

**Limitations**: What can't we know from this data? What assumptions are we \
making? What additional data would we need?

### Question 2: Designing a Proper A/B Test for Promo Codes
**Problem Statement**: Why is the current promo code analysis insufficient? \
What confounds exist?

**Analysis**: Reference the current promo code data from the report. \
Identify:
- current sample sizes and power levels,
- confounding variables (platform, creator size, content type, timing),
- what the observational data suggests (with appropriate caveats).

**Test Design**: Provide a complete A/B test specification:
- null and alternative hypotheses,
- primary and secondary outcome metrics,
- required sample size calculation (based on observed effect sizes and \
desired power of 80%),
- randomization strategy,
- stratification variables,
- minimum detectable effect size,
- test duration estimate,
- analysis plan (including what statistical tests to use),
- guardrail metrics (what to monitor to ensure the test isn't harmful).

**Limitations**: What threats to validity remain even with a proper test? \
What practical constraints might affect execution?

### Question 3: Statistically Insignificant Findings and Re-verification Priority
**Problem Statement**: Why does statistical insignificance matter for \
decision-making? What is the cost of acting on noise?

**Analysis**: Identify ALL findings from the report that are:
- marked as "Hypothesis" evidence level,
- have power below 50%,
- have wide confidence intervals crossing zero,
- are based on sample sizes below 20.

For each, state:
- the finding and its table ID,
- the sample size and power,
- the confidence interval,
- the practical significance (would it matter if true?).

**Re-verification Priority Ranking**: Rank the findings by priority for \
re-verification based on:
1. potential business impact if the finding is real,
2. feasibility of collecting more data,
3. current distance from statistical significance,
4. cost of being wrong (acting on a false positive vs. missing a true effect).

Provide the top 3-5 findings to re-verify first, with a brief justification \
for each.

**Actionable Steps**: For each priority finding, describe:
- what additional data to collect,
- the required sample size for a definitive test,
- the estimated timeline to reach that sample size,
- interim decision guidance (what to do while waiting for more data).

**Limitations**: Acknowledge the multiple comparisons problem and the \
inherent limitations of observational data.

## STYLE RULES
- Write in a professional, direct tone suitable for a portfolio review.
- Use numbered lists for steps, bullet points for analysis.
- Include specific numbers from the data — never say "the data shows" \
without following with the actual number.
- Use tables for comparisons when comparing more than 2 items.
- Keep each answer to 400-600 words.
- End each answer with a one-sentence bottom line.

## REPORT DATA
{report_data}

## FUNNEL DATA
{funnel_data}
"""
