"""Prompt templates for correlation and textual analysis via Claude."""

CORRELATION_ANALYSIS_PROMPT = """\
You are a senior marketing analyst specializing in influencer marketing for EdTech.

You are given:
1. A cleaned JSON dataset of TripleTen advertising integrations.
2. Pre-computed aggregation tables generated by code.

Important analytical guardrails:
- Treat `Traffic Fact`, `Contacts Fact`, `has_contacts`, `cost_per_contact`, and `traffic_to_contact_rate` as the PRIMARY response outcomes for content analysis.
- Treat `Deals Fact`, `Purchase F - TOTAL`, and `cost_per_purchase` as DOWNSTREAM outcomes only.
- Never claim that content directly caused purchases. Use language such as "associated with", "linked to", or "appears alongside".
- Use the table `Scope`, `N`, `Method`, `Evidence`, and `Caveat` fields when interpreting each table.
- If a table is marked exploratory or descriptive-only, say so plainly.
- Do not recompute the table numbers yourself. Use the pre-computed values exactly as provided.

## WHAT TO DELIVER
Write a business-friendly report in English with clear sections and short explanations.

### 1. Executive Summary
Provide 5 concise bullets.
Each bullet must mention:
- the finding,
- the relevant scope,
- the confidence badge (`Reliable signal`, `Probable signal`, or `Hypothesis`),
- and whether it applies to response outcomes or downstream outcomes.

### 2. Content Influence on Response
Focus on the tables tied to response outcomes such as contacts, traffic, and cost per contact.
For each important pattern:
- explain the pattern in plain language,
- cite the relevant table id(s),
- mention the scope and sample size,
- mention the confidence badge,
- explain why the pattern matters operationally.

### 3. Downstream Sales Outcomes
Discuss purchases, deals, and cost per purchase cautiously.
Frame all purchase-related observations as downstream associations, not direct causal proof.
If the data is thin, say that these are hypotheses for further validation.

### 4. Platform and Format Readout
Compare YouTube long-form, short-form, and cross-platform-comparable views only when the table scope allows it.
Do not compare YouTube-only variables such as integration position to Reels/TikTok.
Explicitly note when TikTok is descriptive-only.

### 5. Funnel and Operational Implications
Explain where the biggest downstream drop-offs happen in the funnel.
Separate content-response issues from sales-operations issues whenever possible.

### 6. Recommendations
Provide:
- creative recommendations for improving response outcomes,
- operational recommendations for lower-funnel issues,
- platform-specific next steps,
- and 3 testable hypotheses.

## STYLE RULES
- Be specific and numeric.
- Use short paragraphs and compact bullets.
- Prefer plain language over statistical jargon.
- If mentioning statistics, translate them into simple language.
- Do not invent missing values.
- If evidence is weak, say so.

## PRE-COMPUTED TABLES
The following tables were computed by code from the merged dataset.
Use these exact numbers and metadata.

{precomputed_tables}

## RAW DATA
Use the raw JSON only for qualitative examples and individual case references.
Do not recompute core tables from scratch.

{data_json}
"""


TEXTUAL_REPORT_PROMPT = """\
You are a senior marketing analyst specializing in influencer marketing for EdTech.

You are given:
1. An existing quantitative analysis report.
2. A textual comparison between integrations with and without purchases.
3. Integration context for each textual sample.

Important guardrails:
- Treat textual findings as evidence of messaging patterns, not proof of causality.
- When referencing purchases, use language like "associated with winners" or "appears more often in winner texts".
- When the sample is small, say that the pattern is exploratory.
- Use the pre-computed textual tables exactly as given.

## TASK
Write a standalone textual analysis report in English that:
- explains what linguistic patterns appear in stronger integrations,
- connects those patterns to business actions,
- and stays cautious about overclaiming.

## REQUIRED SECTIONS
- Executive Summary
- Opening Patterns
- Transition Styles
- Persuasion Architecture
- Benefit Framings
- Pain Points
- CTA Formulations
- Text Statistics
- Specificity and Evidence
- Cross-Reference with Existing Analysis
- Winning Script Template
- Anti-Patterns
- Brief Recommendations

## STYLE RULES
- Be specific, concrete, and practical.
- Quote real phrases when available.
- Prefer "associated with" over causal wording.
- Mention sample-size limits when relevant.
- Avoid claiming phrase-level purchase lift unless the tables directly support it.

## PRE-COMPUTED TEXTUAL TABLES
{precomputed_textual_tables}

## EXISTING ANALYSIS REPORT
{existing_report}

## TEXTUAL COMPARISON DATA
{textual_comparison_json}

## INTEGRATION CONTEXT
{integration_context_json}
"""
